import pytest
from pyfun.day01_idioms import (
    even_squares,
    word_lengths,
    unique_first_letters,
    flatten,
    stream_sum_of_squares,
    User,
    Rectangle
)


def test_even_squares():
    assert even_squares([1, 2, 3, 4]) == [4, 16]
    assert even_squares([]) == []
    assert even_squares([1, 3, 5]) == []  # all odd


def test_word_lengths():
    assert word_lengths(["hi", "bye"]) == {"hi": 2, "bye": 3}
    # Last duplicate wins:
    assert word_lengths(["a", "a"]) == {"a": 1}


def test_unique_first_letters():
    assert unique_first_letters(["Apple", "ant", "Banana"]) == {"a", "b"}
    assert unique_first_letters([""]) == set()  # filter excludes empty


def test_flatten():
    assert flatten([[1, 2], [3, 4]]) == [1, 2, 3, 4]
    assert flatten([]) == []


def test_stream_sum_of_squares():
    assert stream_sum_of_squares(5) == 0 + 1 + 4 + 9 + 16





def test_user_equality():
    """Structural equality — generated by dataclass."""
    assert User("Alice", 30) == User("Alice", 30)
    assert User("Alice", 30) != User("Alice", 31)


def test_user_frozen():
    u = User("Alice", 30)
    with pytest.raises(Exception):  # FrozenInstanceError
        u.age = 31  # type: ignore[misc]


def test_user_separate_tag_lists():
    """Critical: each instance gets its own list, not a shared one."""
    a = User("Alice", 30)
    b = User("Bob", 25)
    a.tags.append("admin")  # type: ignore[attr-defined]
    # Wait — this won't work because frozen=True. Let's verify:
    # Actually, frozen prevents attribute reassignment but the list itself is mutable.
    # The point: a.tags and b.tags are DIFFERENT list objects.
    assert a.tags is not b.tags


def test_rectangle_validation():
    r = Rectangle(3, 4)
    assert r.area == 12.0
    with pytest.raises(ValueError):
        Rectangle(-1, 4)


import math
from pyfun.day01_idioms import (
    dot_product_manual,
    dot_product_geometric,
    cosine_similarity,
    angle_between_degrees,
)


def test_dot_product_manual_basic():
    assert dot_product_manual([1, 2, 3], [4, 5, 6]) == 32


def test_dot_product_definitions_agree():
    """Algebraic and geometric definitions give the same number."""
    a, b = [1.0, 2.0, 3.0], [4.0, 5.0, 6.0]
    algebraic = dot_product_manual(a, b)
    geometric = dot_product_geometric(a, b)
    assert math.isclose(algebraic, geometric, rel_tol=1e-9)


def test_orthogonal_vectors_zero_dot():
    """Perpendicular vectors → dot product 0 → angle 90°."""
    assert dot_product_manual([1, 0], [0, 1]) == 0
    assert math.isclose(cosine_similarity([1, 0], [0, 1]), 0.0)
    assert math.isclose(angle_between_degrees([1, 0], [0, 1]), 90.0)


def test_parallel_vectors_cosine_one():
    """Same direction → cosine 1 → angle 0°."""
    assert math.isclose(cosine_similarity([1, 2, 3], [2, 4, 6]), 1.0)
    assert math.isclose(angle_between_degrees([1, 2, 3], [2, 4, 6]), 0.0, abs_tol=1e-9)


def test_opposite_vectors_cosine_negative_one():
    """Opposite direction → cosine -1 → angle 180°."""
    assert math.isclose(cosine_similarity([1, 0], [-1, 0]), -1.0)
    assert math.isclose(angle_between_degrees([1, 0], [-1, 0]), 180.0)


def test_self_dot_is_squared_norm():
    """a · a = ||a||²"""
    a = [3.0, 4.0]
    assert dot_product_manual(a, a) == 25  # 3² + 4² = 9 + 16
    assert math.isclose(math.sqrt(dot_product_manual(a, a)), 5.0)